import './globals.css'


export const metadata = {
  title: 'Mahmoud Agbaria | Web developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en" className='w-screen overflow-x-hidden'>
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />

      </head>
      <body className='bg-black w-screen text-white'>{children}</body>
    </html>
  )
}
